// import definitions for custom element dependencies
import '@fontsource/roboto-flex';
import '@fontsource/roboto';
import '@shoelace-style/shoelace/dist/themes/light.css';
import '@shoelace-style/shoelace/dist/components/button/button.js';
import '@shoelace-style/shoelace/dist/components/checkbox/checkbox.js';
import '@shoelace-style/shoelace/dist/components/radio/radio.js';
import '@shoelace-style/shoelace/dist/components/range/range.js';
import '@shoelace-style/shoelace/dist/components/input/input.js';
import './customElements/aa-styling.scss';

export { AAScreen, type AAScreenValue, type AAScreenValueSubmitEventDetail } from './customElements/aa-screen/aa-screen';
export { AAAffectGrid } from './customElements/aa-affect-grid/aa-affect-grid';
export { AABaseElement } from './customElements/aa-base-element/aa-base-element';
export { AACamera } from './customElements/aa-camera/aa-camera';
export { AACheckboxes } from './customElements/aa-checkboxes/aa-checkboxes';
export { AAChoiceItem } from './customElements/aa-choice-item/aa-choice-item';
export { AAMultipleChoice } from './customElements/aa-multiple-choice/aa-multiple-choice';
export { AAChoose } from './customElements/aa-choose/aa-choose';
export { AAWhen } from './customElements/aa-choose/aa-when/aa-when';
export { AAOtherwise } from './customElements/aa-choose/aa-otherwise/aa-otherwise';
export { AAFunctionRandom } from './customElements/aa-function/aa-function-random';
export { AAGeolocation } from './customElements/aa-geolocation/aa-geolocation';
export { AALabel } from './customElements/aa-label/aa-label';
export { AALikertScale } from './customElements/aa-likert-scale/aa-likert-scale';
export { AAMemory } from './customElements/aa-memory/aa-memory';
export { AASequence } from './customElements/aa-sequence/aa-sequence';
export { AAJump } from './customElements/aa-sequence/aa-jump/aa-jump';
export { AASession, type AASessionInput, type AASessionInputSubmitEventDetail } from './customElements/aa-session/aa-session';
export { AAScheduleCalendar } from './customElements/aa-schedule-calendar/aa-schedule-calendar';
export { AASignalProtocol, type SignalProtocolConfig } from './customElements/aa-signal-protocol/aa-signal-protocol';
export { AASlider } from './customElements/aa-slider/aa-slider';
export { AATextAnswer } from './customElements/aa-text-answer/aa-text-answer';
export { AAVariable } from './customElements/aa-variable/aa-variable';