// import '../dist/paper-polymer.js';
import  './customElements/aa-baseElement/baseElement.js';
import  './customElements/aa-variable/aa-variable.js';
import  './customElements/aa-function/aa-function-random.js';
import  './customElements/aa-choose/aa-choose.js';
import  './customElements/aa-memory/aa-memory.js';
import  './customElements/aa-screen/aa-screen.js';
import  './customElements/aa-sequence/aa-sequence.js';
import  './customElements/aa-session/aa-session.js';
import  './customElements/aa-text-answer/aa-text-answer.js';
